name: Build RimWorld Mod DLL

################################################################################
# Change these only if your folder layout moves
################################################################################
env:
  MOD_SRC_PATH: Source/1.6           # folder with the .csproj
  DLL_OUT_PATH: Source/1.6/Assemblies  # <-- corrected
  ARTIFACT_NAME: MyMenuButtonModDLL

################################################################################
# Build on pushes and pull requests (skip README edits)
################################################################################
on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - 'README.md'
  pull_request:

################################################################################
# Compile on Windows (needs .NET Framework ref-packs) and upload the DLL
################################################################################
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore packages
        run: dotnet restore "${{ env.MOD_SRC_PATH }}"

      # Build in Release mode and copy DLL to Source/1.6/Assemblies/
      - name: Build (Release)
        run: >
          dotnet build "${{ env.MOD_SRC_PATH }}"
          --configuration Release
          --no-restore
          '/p:OutDir=$(ProjectDir)..\..\Assemblies\'


      # Upload the compiled DLL
      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.DLL_OUT_PATH }}/*.dll
