name: Build RimWorld Mod DLL

env:
  MOD_SRC_PATH: MyMenuButtonMod/Source/1.6
  DLL_OUT_PATH: MyMenuButtonMod/1.6/Assemblies
  ARTIFACT_NAME: MyMenuButtonModDLL

on:
  push:
    branches: [ master, main ]
    paths-ignore:
      - "README.md"
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore packages
        run: dotnet restore "${{ env.MOD_SRC_PATH }}"

      - name: Build
        run: dotnet build "${{ env.MOD_SRC_PATH }}" --configuration Release --no-restore

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: |
            ${{ env.DLL_OUT_PATH }}/*.dll
