name: Build RimWorld Mod DLL

env:
  # Folder that contains your .csproj (now at the repo root)
  MOD_SRC_PATH: Source/1.6
  # Where the DLL ends up after the Release build
  DLL_OUT_PATH: Source/1.6/bin/Release
  ARTIFACT_NAME: MyMenuButtonModDLL

on:
  push:
    branches: [ master, main ]
    paths-ignore:
      - "README.md"
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore packages
        run: dotnet restore "${{ env.MOD_SRC_PATH }}"

      - name: Build (Release)
        run: dotnet build "${{ env.MOD_SRC_PATH }}" --configuration Release --no-restore

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: |
            ${{ env.DLL_OUT_PATH }}/**/*.dll
